#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2000 Graeme S. Roy <graeme@epc.co.uk>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.


# UNIX shell script to build a PKG package file


# $Id: build,v 1.31 2000-10-11 18:04:18 graeme Exp $


version=1.3.0
libversion=1.3


# Build the mpatrol library.

cd ../../build/unix
make clobber
make libmpatrol.a libmpatrol.so.$libversion
make libmpatrolmt.a libmpatrolmt.so.$libversion
make llib-lmpatrol.ln llib-lmpatrolmt.ln
make mpatrol mprof mleak
cd ../../pkg/pkg


# Create the installation directory structure and copy the necessary
# files into it.  This assumes that the Texinfo manual has already been
# processed into the different documentation formats.

rm -rf bin doc include info lib man
mkdir -p bin
cp ../../build/unix/mpatrol bin
cp ../../build/unix/mprof bin
cp ../../build/unix/mleak bin
mkdir -p doc/mpatrol/images
cp ../../README doc/mpatrol
cp ../../doc/README doc/mpatrol/README.DOC
cp ../../COPYING doc/mpatrol
cp ../../COPYING.LIB doc/mpatrol
cp ../../NEWS doc/mpatrol
cp ../../ChangeLog doc/mpatrol
cp ../../doc/mpatrol.txt doc/mpatrol
cp ../../doc/mpatrol.guide doc/mpatrol
cp ../../doc/mpatrol.html doc/mpatrol
cp ../../doc/mpatrol.dvi doc/mpatrol
cp ../../doc/mpatrol.ps doc/mpatrol
cp ../../doc/mpatrol.pdf doc/mpatrol
cp ../../doc/refcard.dvi doc/mpatrol
cp ../../doc/refcard.ps doc/mpatrol
cp ../../doc/refcard.pdf doc/mpatrol
cp ../../doc/images/mpatrol.txt doc/mpatrol/images
cp ../../doc/images/mpatrol.jpg doc/mpatrol/images
cp ../../doc/images/mpatrol.eps doc/mpatrol/images
cp ../../doc/images/mpatrol.png doc/mpatrol/images
mkdir -p doc/mpatrol/tests/pass
cp ../../tests/pass/test*.c doc/mpatrol/tests/pass
mkdir -p doc/mpatrol/tests/fail
cp ../../tests/fail/test*.c doc/mpatrol/tests/fail
mkdir -p doc/mpatrol/tests/profile
cp ../../tests/profile/test*.c doc/mpatrol/tests/profile
mkdir -p doc/mpatrol/tests/tutorial
cp ../../tests/tutorial/test*.c doc/mpatrol/tests/tutorial
mkdir -p include
cp ../../src/mpatrol.h include
mkdir -p info
cp ../../doc/mpatrol.info info
mkdir -p lib
cp ../../build/unix/libmpatrol.a lib
cp ../../build/unix/libmpatrol.so.$libversion lib
cp ../../build/unix/libmpatrolmt.a lib
cp ../../build/unix/libmpatrolmt.so.$libversion lib
cp ../../build/unix/llib-lmpatrol.ln lib
cp ../../build/unix/llib-lmpatrolmt.ln lib
mkdir -p man/man1
cp ../../man/man1/mpatrol.1 man/man1
cp ../../man/man1/mprof.1 man/man1
cp ../../man/man1/mleak.1 man/man1
mkdir -p man/man3
cp ../../man/man3/mpatrol.3 man/man3


# Create the package within a package directory structure.

rm -rf GSRmptrl
pkgmk -d`pwd` -r`pwd` GSRmptrl
rm -rf bin doc include info lib man


# Convert the package directory structure to a package file.

rm -f mpatrol-$version.pkg
pkgtrans -s `pwd` mpatrol-$version.pkg GSRmptrl
rm -rf GSRmptrl


# Clean up the build directory.

cd ../../build/unix
make clobber
cd ../../pkg/pkg
