#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2000 Graeme S. Roy <graeme@epc.co.uk>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.


# UNIX shell script to build a PKG package file


# $Id: build,v 1.10 2000-03-30 18:08:27 graeme Exp $


version=1.1.3
libversion=1.1


# Build the mpatrol library.

cd ../../build/unix
make clobber
make libmpatrol.a libmpatrol.so.$libversion memleak
cd ../../pkg/pkg


# Create the installation directory structure and copy the necessary
# files into it.  This assumes that the Texinfo manual has already been
# processed into the different documentation formats.

rm -rf bin doc include info lib man
mkdir -p bin
cp ../../bin/mpatrol bin
cp ../../build/unix/memleak bin
mkdir -p doc/mpatrol/images
cp ../../README doc/mpatrol
cp ../../doc/README doc/mpatrol/README.DOC
cp ../../FAQ doc/mpatrol
cp ../../COPYING doc/mpatrol
cp ../../COPYING.LIB doc/mpatrol
cp ../../NEWS doc/mpatrol
cp ../../ChangeLog doc/mpatrol
cp ../../doc/mpatrol.txt doc/mpatrol
cp ../../doc/mpatrol.guide doc/mpatrol
cp ../../doc/mpatrol.html doc/mpatrol
cp ../../doc/mpatrol.dvi doc/mpatrol
cp ../../doc/mpatrol.ps doc/mpatrol
cp ../../doc/mpatrol.pdf doc/mpatrol
cp ../../doc/images/mpatrol.jpg doc/mpatrol/images
cp ../../doc/images/mpatrol.eps doc/mpatrol/images
cp ../../doc/images/mpatrol.pdf doc/mpatrol/images
mkdir -p include
cp ../../src/mpatrol.h include
mkdir -p info
cp ../../doc/mpatrol.info info
mkdir -p lib
cp ../../build/unix/libmpatrol.a lib
cp ../../build/unix/libmpatrol.so.$libversion lib
mkdir -p man/man1
cp ../../man/man1/mpatrol.1 man/man1
cp ../../man/man1/memleak.1 man/man1
mkdir -p man/man3
cp ../../man/man3/mpatrol.3 man/man3


# Create the package within a package directory structure.

rm -rf GSRmptrl
pkgmk -d. -r. GSRmptrl
rm -rf bin doc include info lib man


# Convert the package directory structure to a package file.

rm -f mpatrol-$version.pkg
pkgtrans -s . mpatrol-$version.pkg GSRmptrl
rm -rf GSRmptrl


# Clean up the build directory

cd ../../build/unix
make clobber
cd ../../pkg/pkg
