#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2001 Graeme S. Roy <graeme@epc.co.uk>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.


# UNIX shell script to build a SD/UX package file


# $Id: build,v 1.17 2001-01-25 23:15:11 graeme Exp $


version=1.3.4


# Build the mpatrol library.

cd ../../build/unix
make clobber
make libmpatrol.a libmpatrol.sl
make libmpalloc.a libmpalloc.sl
make mpatrol mprof mptrace mleak
strip mpatrol
strip mprof
strip mptrace
strip mleak
cd ../../pkg/sdux


# Create the installation directory structure and copy the necessary
# files into it.  This assumes that the Texinfo manual, reference card
# and manual pages have already been processed into the different
# documentation formats.

rm -rf mpatrol
mkdir -p mpatrol/bin
cp ../../build/unix/mpatrol mpatrol/bin
cp ../../build/unix/mprof mpatrol/bin
cp ../../build/unix/mptrace mpatrol/bin
cp ../../build/unix/mleak mpatrol/bin
cp ../../bin/mpsym mpatrol/bin
cp ../../bin/mpedit mpatrol/bin
cp ../../bin/hexwords mpatrol/bin
mkdir -p mpatrol/doc/mpatrol/images
cp ../../README mpatrol/doc/mpatrol
cp ../../doc/README mpatrol/doc/mpatrol/README.DOC
cp ../../man/README mpatrol/doc/mpatrol/README.MAN
cp ../../COPYING mpatrol/doc/mpatrol
cp ../../COPYING.LIB mpatrol/doc/mpatrol
cp ../../NEWS mpatrol/doc/mpatrol
cp ../../ChangeLog mpatrol/doc/mpatrol
cp ../../doc/mpatrol.txt mpatrol/doc/mpatrol
cp ../../doc/mpatrol.guide mpatrol/doc/mpatrol
cp ../../doc/mpatrol.html mpatrol/doc/mpatrol
cp ../../doc/mpatrol.dvi mpatrol/doc/mpatrol
cp ../../doc/mpatrol.ps mpatrol/doc/mpatrol
cp ../../doc/mpatrol.pdf mpatrol/doc/mpatrol
cp ../../doc/refcard.dvi mpatrol/doc/mpatrol
cp ../../doc/refcard.ps mpatrol/doc/mpatrol
cp ../../doc/refcard.pdf mpatrol/doc/mpatrol
cp ../../doc/images/mpatrol.txt mpatrol/doc/mpatrol/images
cp ../../doc/images/mpatrol.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/mpatrol.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/mpatrol.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/test.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/test.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/test.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/gcc.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/gcc.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/gcc.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/cpp.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/cpp.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/cpp.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/cc1.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/cc1.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/cc1.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/collect2.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/collect2.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/collect2.pdf mpatrol/doc/mpatrol/images
cp ../../doc/images/trace.jpg mpatrol/doc/mpatrol/images
cp ../../doc/images/trace.eps mpatrol/doc/mpatrol/images
cp ../../doc/images/trace.pdf mpatrol/doc/mpatrol/images
mkdir -p mpatrol/doc/mpatrol/html
cp ../../man/html/mpatrol.html mpatrol/doc/mpatrol/html
cp ../../man/html/mprof.html mpatrol/doc/mpatrol/html
cp ../../man/html/mptrace.html mpatrol/doc/mpatrol/html
cp ../../man/html/mleak.html mpatrol/doc/mpatrol/html
cp ../../man/html/mpsym.html mpatrol/doc/mpatrol/html
cp ../../man/html/mpedit.html mpatrol/doc/mpatrol/html
cp ../../man/html/hexwords.html mpatrol/doc/mpatrol/html
cp ../../man/html/libmpatrol.html mpatrol/doc/mpatrol/html
mkdir -p mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mpatrol.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mprof.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mptrace.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mleak.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mpsym.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/mpedit.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/hexwords.dvi mpatrol/doc/mpatrol/dvi
cp ../../man/dvi/libmpatrol.dvi mpatrol/doc/mpatrol/dvi
mkdir -p mpatrol/doc/mpatrol/ps
cp ../../man/ps/mpatrol.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/mprof.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/mptrace.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/mleak.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/mpsym.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/mpedit.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/hexwords.ps mpatrol/doc/mpatrol/ps
cp ../../man/ps/libmpatrol.ps mpatrol/doc/mpatrol/ps
mkdir -p mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mpatrol.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mprof.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mptrace.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mleak.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mpsym.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/mpedit.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/hexwords.pdf mpatrol/doc/mpatrol/pdf
cp ../../man/pdf/libmpatrol.pdf mpatrol/doc/mpatrol/pdf
mkdir -p mpatrol/doc/mpatrol/tests/pass
cp ../../tests/pass/test*.c mpatrol/doc/mpatrol/tests/pass
mkdir -p mpatrol/doc/mpatrol/tests/fail
cp ../../tests/fail/test*.c mpatrol/doc/mpatrol/tests/fail
mkdir -p mpatrol/doc/mpatrol/tests/profile
cp ../../tests/profile/test*.c mpatrol/doc/mpatrol/tests/profile
mkdir -p mpatrol/doc/mpatrol/tests/tutorial
cp ../../tests/tutorial/test*.c mpatrol/doc/mpatrol/tests/tutorial
mkdir -p mpatrol/include
cp ../../src/mpatrol.h mpatrol/include
cp ../../src/mpalloc.h mpatrol/include
mkdir -p mpatrol/info
cp ../../doc/mpatrol.info mpatrol/info
mkdir -p mpatrol/lib
cp ../../build/unix/libmpatrol.a mpatrol/lib
cp ../../build/unix/libmpatrol.sl mpatrol/lib
cp ../../build/unix/libmpalloc.a mpatrol/lib
cp ../../build/unix/libmpalloc.sl mpatrol/lib
mkdir -p mpatrol/man/man1
cp ../../man/man1/mpatrol.1 mpatrol/man/man1
cp ../../man/man1/mprof.1 mpatrol/man/man1
cp ../../man/man1/mptrace.1 mpatrol/man/man1
cp ../../man/man1/mleak.1 mpatrol/man/man1
cp ../../man/man1/mpsym.1 mpatrol/man/man1
cp ../../man/man1/mpedit.1 mpatrol/man/man1
cp ../../man/man1/hexwords.1 mpatrol/man/man1
mkdir -p mpatrol/man/man3
cp ../../man/man3/libmpatrol.3 mpatrol/man/man3


# Create the package file.  You must have root permission or be able to
# modify the Access Control Lists in order to perform this step.

rm -f mpatrol-$version.depot.gz
swpackage -d "| gzip >mpatrol-$version.depot.gz" -x target_type=tape -s mpatrol.psf
rm -rf mpatrol


# Clean up the build directory.

cd ../../build/unix
make clobber
cd ../../pkg/sdux
